default:
  tags:
    - smatflow-projects-runner

stages:
  - deploy-dev

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

.deploy:
  image: python:3.10
  rules:
    - if: $CI_COMMIT_TAG || ($CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /^Merge branch.*/)
    - if: $CI_PIPELINE_SOURCE == "web"
    # - if: $CI_PIPELINE_SOURCE == "web"  &&  $CI_COMMIT_BRANCH == "main"

  cache:
    key: pip-cache
    paths:
      - .cache/pip
  before_script:
    - bash cicd_vars.sh

    - pip install --upgrade pip

    - pip install ansible

    - export ANSIBLE_HOST_KEY_CHECKING=False

    - eval $(ssh-agent -s)

    - ssh-add <(echo "$ANSIBLE_DEPLOY_KEY")

  script:
    - ansible-playbook -u "$ANSIBLE_SERVER_USER" -i "$ANSIBLE_SERVER_HOST," ansible/playbook.yml --extra-vars "repo_url=$CI_REPOSITORY_URL"

deploy-dev:
  extends: .deploy
  stage: deploy-dev
  environment:
    name: development
  when: always
